### ISSUE TITLE
Case selection

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_macrointerest#14]
> R2: Why are only 37 OECD countries included in the analysis? The main advantage of creating the country-year estimates based on multiple survey sources is to broaden the scope of research beyond the well-surveyed countries. Restricting the analysis to just 37 countries, and ones that are the most frequently surveyed, contradicts this purpose. Why not just take ESS data, which include most of the OECD countries, and save ourselves all the harmonization effort? I think the otherwise interesting analysis does not very well demonstrate the unique research opportunities created by the harmonized macro-interest time series. This unique opportunity is, to my understanding, to compare countries which do not participate in the same survey projects.

- [x] Literature reasons
- [x] Data reasons
- [x] Welcome to future researchers' replication in other data

**Comment by fsolt** [comment]
Thanks for your work on this, Hu.  I think that maybe what is needed here, rather than (or probably in addition to) a long appendix, is a sentence or two (ugh—word count #23 again) in the text highlighting how much better coverage our macrointerest data has than ESS and other sources even in this relatively small, data-rich sample.  I'll work on that.

**Comment by fsolt** [comment]
Closed by d605d65
