### ISSUE TITLE
Data-density variant cases

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_macrointerest#16]
> R2: Based on Figure A1 it looks like the least frequently surveyed countries in the dataset (Kosovo, Azerbaijan, Cambodia) will likely have huge uncertainty around the estimated trajectory of macrointerest. I think the appendix should show the trajectories for all countries (an extension of Figure 4 to all countries), so readers can assess the benefits of having very rarely surveyed countries in the analysis. E.g. Puerto Rico has surveys from 1995, 2001 and 2018, so there is a lot of imputation going on there.

> Figure A1: Why is Northern Ireland separate form the United Kingdom?

- [x] Show the countries with dense, medium, and rare data
- [ ] Fix the plot to make the reviewer happy

**Comment by sammo3182** [comment]
Fred @fsolt , any specific reason for the Northern Ireland choice?

**Comment by fsolt** [comment]
Some surveys (`ees1989`, `issp1990`, `evs_combo` in this project) include Northern Ireland but don't include a sampling weight to include those respondents in the UK as a whole.  In those cases---unlike in say the Eurobarometer which includes a UK weight for NI respondents that we always use---we have separate source estimates for Britain and for NI.  Since NI is very small relative to Britain, this doesn't really matter for the UK (NI is less than 3% of the UK by population).  And we've generally gone ahead and used those NI source data to make estimates for NI alone, even though hypothetically if we really wanted NI estimates we would also get source data from e.g. the Eurobarometer.  I'm sure it makes no difference---the NI-only data isn't really rich enough to have an influence the difficulty and dispersion parameters and so the estimates of other countries (I see in this case there is one year with two items, so it might matter a *tiny, tiny* bit).  I guess we should just drop it to avoid having to talk about it.

**Comment by fsolt** [comment]
Ugh, we're not really going to be able to avoid having to talk about it.
